title: "Nederland-Bewust"
description: "Dé startpagina voor alternatieve zorg, holistische therapie, natuurlijke gezondheid én welzijn in Nederland."
baseurl: "/nederland-bewust"
url: "https://hands4flownl.github.io"

lang: nl
timezone: Europe/Amsterdam
markdown: kramdown
highlighter: rouge
permalink: pretty

formspree_endpoint: "https://formspree.io/f/JOUWFORMID"

contact:
  marcella: "06-21312490"
  elsemarie: "06-59111456"
  email: "info@nederland-bewust.nl"
  facebook: "https://www.facebook.com/share/1NK76U1wML/"
  instagram: "https://instagram.com/nederlandbewust2026"
  whatsapp: "https://wa.me/31659111456"

collections:
  bewust-makers:
    output: true
    permalink: /bewust-makers/:slug/
  agenda:
    output: true
    permalink: /activiteiten/:slug/

defaults:
  - scope:
      path: ""
      type: "bewust-makers"
    values:
      layout: "bewust-maker"
      gepubliceerd: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - netlify.toml
  - _config_netlify.yml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
